### ISSUE TITLE
configure paste url 

### ISSUE THREAD

**Issue by alex-leonhardt** [bartTC/dpasteGUI#5]
Hi,

thanks for the gui - i am trying to change the paste url to go to a internal dpaste -- I know nothing about this app or how to compile it - do you have any doc on how to do this (for mac os x) ? 

Thanks
Alex

**Comment by bartTC** [comment]
It's fairly easy. Download the repository. Open it in Xcode. All you need to do is to change the URL in this line https://github.com/bartTC/dpasteGUI/blob/master/AppManager.m#L80 and compile it. 

I just did it on Sierra and it all still works, despite the fairly old code base.

If I ever manage to update this app, I make this URL a setting. I'd likely start with a new Project though, based on Swift though.
